package com.fanfan.robot.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fanfan.robot.model.VoiceBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VOICE_BEAN".
*/
public class VoiceBeanDao extends AbstractDao<VoiceBean, Long> {

    public static final String TABLENAME = "VOICE_BEAN";

    /**
     * Properties of entity VoiceBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LocalType = new Property(1, int.class, "localType", false, "localType");
        public final static Property SaveTime = new Property(2, long.class, "saveTime", false, "saveTime");
        public final static Property ShowTitle = new Property(3, String.class, "showTitle", false, "showTitle");
        public final static Property VoiceAnswer = new Property(4, String.class, "voiceAnswer", false, "voiceanswer");
        public final static Property ImgUrl = new Property(5, String.class, "imgUrl", false, "imgUrl");
        public final static Property Action = new Property(6, String.class, "action", false, "action");
        public final static Property Expression = new Property(7, String.class, "expression", false, "expression");
        public final static Property ActionData = new Property(8, String.class, "actionData", false, "actionData");
        public final static Property ExpressionData = new Property(9, String.class, "expressionData", false, "expressionData");
        public final static Property Key1 = new Property(10, String.class, "key1", false, "key1");
        public final static Property Key2 = new Property(11, String.class, "key2", false, "key2");
        public final static Property Key3 = new Property(12, String.class, "key3", false, "key3");
        public final static Property Key4 = new Property(13, String.class, "key4", false, "key4");
    }


    public VoiceBeanDao(DaoConfig config) {
        super(config);
    }
    
    public VoiceBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VOICE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"localType\" INTEGER NOT NULL ," + // 1: localType
                "\"saveTime\" INTEGER NOT NULL ," + // 2: saveTime
                "\"showTitle\" TEXT," + // 3: showTitle
                "\"voiceanswer\" TEXT," + // 4: voiceAnswer
                "\"imgUrl\" TEXT," + // 5: imgUrl
                "\"action\" TEXT," + // 6: action
                "\"expression\" TEXT," + // 7: expression
                "\"actionData\" TEXT," + // 8: actionData
                "\"expressionData\" TEXT," + // 9: expressionData
                "\"key1\" TEXT," + // 10: key1
                "\"key2\" TEXT," + // 11: key2
                "\"key3\" TEXT," + // 12: key3
                "\"key4\" TEXT);"); // 13: key4
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VOICE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VoiceBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLocalType());
        stmt.bindLong(3, entity.getSaveTime());
 
        String showTitle = entity.getShowTitle();
        if (showTitle != null) {
            stmt.bindString(4, showTitle);
        }
 
        String voiceAnswer = entity.getVoiceAnswer();
        if (voiceAnswer != null) {
            stmt.bindString(5, voiceAnswer);
        }
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(6, imgUrl);
        }
 
        String action = entity.getAction();
        if (action != null) {
            stmt.bindString(7, action);
        }
 
        String expression = entity.getExpression();
        if (expression != null) {
            stmt.bindString(8, expression);
        }
 
        String actionData = entity.getActionData();
        if (actionData != null) {
            stmt.bindString(9, actionData);
        }
 
        String expressionData = entity.getExpressionData();
        if (expressionData != null) {
            stmt.bindString(10, expressionData);
        }
 
        String key1 = entity.getKey1();
        if (key1 != null) {
            stmt.bindString(11, key1);
        }
 
        String key2 = entity.getKey2();
        if (key2 != null) {
            stmt.bindString(12, key2);
        }
 
        String key3 = entity.getKey3();
        if (key3 != null) {
            stmt.bindString(13, key3);
        }
 
        String key4 = entity.getKey4();
        if (key4 != null) {
            stmt.bindString(14, key4);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VoiceBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLocalType());
        stmt.bindLong(3, entity.getSaveTime());
 
        String showTitle = entity.getShowTitle();
        if (showTitle != null) {
            stmt.bindString(4, showTitle);
        }
 
        String voiceAnswer = entity.getVoiceAnswer();
        if (voiceAnswer != null) {
            stmt.bindString(5, voiceAnswer);
        }
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(6, imgUrl);
        }
 
        String action = entity.getAction();
        if (action != null) {
            stmt.bindString(7, action);
        }
 
        String expression = entity.getExpression();
        if (expression != null) {
            stmt.bindString(8, expression);
        }
 
        String actionData = entity.getActionData();
        if (actionData != null) {
            stmt.bindString(9, actionData);
        }
 
        String expressionData = entity.getExpressionData();
        if (expressionData != null) {
            stmt.bindString(10, expressionData);
        }
 
        String key1 = entity.getKey1();
        if (key1 != null) {
            stmt.bindString(11, key1);
        }
 
        String key2 = entity.getKey2();
        if (key2 != null) {
            stmt.bindString(12, key2);
        }
 
        String key3 = entity.getKey3();
        if (key3 != null) {
            stmt.bindString(13, key3);
        }
 
        String key4 = entity.getKey4();
        if (key4 != null) {
            stmt.bindString(14, key4);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VoiceBean readEntity(Cursor cursor, int offset) {
        VoiceBean entity = new VoiceBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // localType
            cursor.getLong(offset + 2), // saveTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // showTitle
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // voiceAnswer
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imgUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // action
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // expression
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // actionData
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // expressionData
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // key1
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // key2
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // key3
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // key4
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VoiceBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLocalType(cursor.getInt(offset + 1));
        entity.setSaveTime(cursor.getLong(offset + 2));
        entity.setShowTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVoiceAnswer(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImgUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAction(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setExpression(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setActionData(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setExpressionData(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setKey1(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setKey2(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setKey3(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setKey4(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VoiceBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VoiceBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VoiceBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
